# Generated by Django 5.2.7 on 2025-10-11 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_fanphoto_options_alter_fanphoto_caption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fanphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фан-фото', 'verbose_name_plural': 'Фан-фото'},
        ),
        migrations.AlterField(
            model_name='fanphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='fanphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='fanphoto',
            name='image',
            field=models.ImageField(upload_to='fan_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='fanphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_photos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг в URL')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='group_covers/', verbose_name='Обложка')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город / локация')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('meeting_place', models.CharField(blank=True, max_length=255, verbose_name='Место встреч')),
                ('meeting_time', models.CharField(blank=True, max_length=120, verbose_name='Время встреч (как текст)')),
                ('dress_code', models.CharField(blank=True, max_length=255, verbose_name='Дресс-код')),
                ('contacts', models.CharField(blank=True, max_length=255, verbose_name='Контакты (телеграм, инста и т.п.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group', verbose_name='Группа (auth.Group)')),
            ],
            options={
                'verbose_name': 'Профиль группы',
                'verbose_name_plural': 'Профили групп',
                'ordering': ['group__name'],
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
