# Generated by Django 5.2.7 on 2025-10-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clubs', '0004_alter_news_options_remove_news_created_at_and_more'),
        ('users', '0003_alter_fanphoto_options_alter_fanphoto_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'verbose_name': 'Профиль группы', 'verbose_name_plural': 'Профили групп'},
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='dress_code',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='meeting_place',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='slug',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fan_groups', to='clubs.club', verbose_name='Клуб'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='meet_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место встречи'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/', verbose_name='Фото/баннер'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group', verbose_name='Группа'),
        ),
    ]
