# Generated by Django 5.2.7 on 2025-10-12 13:51

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_groupprofile_options_remove_groupprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'ordering': ['group__name'], 'verbose_name': 'Профиль группы', 'verbose_name_plural': 'Профили групп'},
        ),
        migrations.RenameField(
            model_name='fanphoto',
            old_name='image',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.group_cover_upload_to, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.group_avatar_upload_to, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group', verbose_name='Группа (auth.Group)'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.group_photo_upload_to, verbose_name='Фото/баннер'),
        ),
    ]
